-- Auto-generated by nvimvenv
-- Project-local Python configuration (safe)

vim.g.project_python = "/home/trappedintesseract/.virtualenvs/GameHub/bin/python"

-- LSP (pyright / pylsp)
vim.g.python_host_prog = nil
